Repository uyuni-project/uyuni-docs, pull requests merged in 2022-01, with the labels that each got.

#1370 Introduce postgresql 14 with SUMA 4.3 and drop SUMA 4.0 description
  .changelog
  modules/installation-and-upgrade/pages/db-intro.adoc
  modules/installation-and-upgrade/pages/db-migration-xy.adoc
  modules/installation-and-upgrade/pages/server-y-yast.adoc
  modules/installation-and-upgrade/pages/server-y-zypper.adoc
  modules/installation-and-upgrade/pages/server-y.adoc
Labels: manager-4.3

#1375 added no linting option to make_pot.sh and use_po.sh
  make_pot.sh
  use_po.sh
Labels: enhancement

#1376 removed references to caasp
  modules/ROOT/pages/_partials/entities.adoc
  modules/client-configuration/nav-client-configuration-guide.adoc
  modules/client-configuration/pages/system-locking.adoc
  modules/client-configuration/pages/system-types.adoc
  modules/client-configuration/pages/vhm-caasp.adoc
  modules/client-configuration/pages/vhm-kubernetes.adoc
  modules/client-configuration/pages/vhm.adoc
  modules/client-configuration/pages/virt-clusters.adoc
  modules/client-configuration/pages/virtualization.adoc
  modules/reference/nav-reference-guide.adoc
  modules/reference/pages/clusters/clusters-add.adoc
  modules/reference/pages/clusters/clusters-details.adoc
  modules/reference/pages/clusters/clusters-menu.adoc
  modules/reference/pages/clusters/clusters-overview.adoc
Labels: manager-4.3

#1387 backport42 - Adding PAYG documentation
  .changelog
  modules/installation/nav-installation-guide.adoc
  modules/installation/pages/connect-payg.adoc
  modules/quickstart-public-cloud/pages/clients.adoc
  parameters.yml
Labels: manager-4.2

#1382 New content feature Pay-as-you-go
  .changelog
  diff
  modules/installation-and-upgrade/nav-installation-and-upgrade-guide.adoc
  modules/installation-and-upgrade/pages/connect-payg.adoc
  modules/specialized-guides/pages/qs-publiccloud/clients.adoc
  parameters.yml
Labels: manager-4.3
