Repository uyuni-project/uyuni-docs, pull requests merged in 2023-09, with the labels that each got.

#2430 Backport 4.3: CCG salt jinja templating #16905 keichwa (#2420)
  .changelog
  modules/client-configuration/pages/configuration-management.adoc
Labels: manager-4.3

#2438 Image building fixes
  .changelog
  modules/administration/pages/image-management.adoc
Labels: master, manager-4.3

#2427 configure-proxy.sh will not create a configuration channel anymore
  .changelog
  modules/installation-and-upgrade/pages/uyuni-proxy-setup.adoc
Labels: master, 5.0

#2466 Fixed the support matrix in two Guides
  modules/client-configuration/pages/supported-features.adoc
  modules/installation-and-upgrade/pages/client-requirements.adoc
Labels: master, manager-4.3
