Repository uyuni-project/uyuni-docs, pull requests merged in 2023-11, with the labels that each got.

#2617 no section ID in snippets
  modules/administration/pages/snippets/install_scap_security_guide_package.adoc
Labels: 5.0

#2614 Add liberty linux 7 and 8 jcayouette
  .changelog
  modules/client-configuration/pages/supported-features.adoc
  modules/installation-and-upgrade/pages/client-requirements.adoc
Labels: master, manager-4.3

#2615 Add liberty linux 7 and 8 jcayouette manager43
  .changelog
  modules/client-configuration/pages/supported-features.adoc
  modules/installation-and-upgrade/pages/client-requirements.adoc
Labels: manager-4.3

#2579 Ccg virtualization formula #22931
  .changelog
  modules/client-configuration/pages/virt-xenkvm.adoc
  modules/client-configuration/pages/virtualization.adoc
Labels: 5.0

#2631 backport 4.3: CCG virtualization formula #22931 (#2579)
  .changelog
  modules/client-configuration/pages/virt-xenkvm.adoc
  modules/client-configuration/pages/virtualization.adoc
Labels: manager-4.3

#2645 Azure payg jcayouette
  .changelog
  modules/specialized-guides/nav-specialized-guides-guide.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/aws/payg-aws-configure-the-image.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/aws/payg-aws-connections-and-bootstrapping.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/aws/payg-aws-public-cloud-images.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/aws/payg-aws-requirements.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/aws/payg-aws-server-setup.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/aws/payg-aws-webui-configuration.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/azure/payg-azure-configure-the-image.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/azure/payg-azure-connections-and-bootstrapping.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/azure/payg-azure-public-cloud-images.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/azure/payg-azure-requirements.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/azure/payg-azure-server-setup.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/azure/payg-azure-webui-configuration.adoc
  modules/specialized-guides/pages/public-cloud-guide/payg/payg-troubleshooting.adoc
Labels: master, manager-4.3
