Repository uyuni-project/uyuni-docs, pull requests merged in 2023-06, with the labels that each got.

#2259 updated zh_CN locale for traditional attribute in tables
  branding/locale/attributes-zh_CN.adoc
Labels: master, manager-4.2, manager-4.3

#2263 add snippet for create_bootstrap_repo_register
  modules/client-configuration/pages/clients-alibaba.adoc
  modules/client-configuration/pages/clients-almalinux.adoc
  modules/client-configuration/pages/clients-amazon.adoc
  modules/client-configuration/pages/clients-centos.adoc
  modules/client-configuration/pages/clients-debian.adoc
  modules/client-configuration/pages/clients-opensuseleap.adoc
  modules/client-configuration/pages/clients-opensuseleapmicro.adoc
  modules/client-configuration/pages/clients-oracle.adoc
  modules/client-configuration/pages/clients-rh-cdn.adoc
  modules/client-configuration/pages/clients-rh-rhui.adoc
  modules/client-configuration/pages/clients-rocky.adoc
  modules/client-configuration/pages/clients-sle.adoc
  modules/client-configuration/pages/clients-slemicro.adoc
  modules/client-configuration/pages/clients-sleses.adoc
  modules/client-configuration/pages/clients-ubuntu-old.adoc
  modules/client-configuration/pages/clients-ubuntu.adoc
  modules/client-configuration/pages/snippets/create_bootstrap_repo_register.adoc
Labels: master

#2292 removed two outdated tech previews
  Release.key
  Release.key.1
  Release.key.10
  Release.key.11
  Release.key.12
  Release.key.13
  Release.key.14
  Release.key.15
  Release.key.16
  Release.key.17
  Release.key.18
  Release.key.19
  Release.key.2
  Release.key.20
  Release.key.21
  Release.key.22
  Release.key.23
  Release.key.24
  Release.key.25
  Release.key.26
  Release.key.27
  Release.key.28
  Release.key.29
  Release.key.3
  Release.key.30
  Release.key.31
  Release.key.32
  Release.key.33
  Release.key.34
  Release.key.35
  Release.key.36
  Release.key.37
  Release.key.38
  Release.key.4
  Release.key.5
  Release.key.6
  Release.key.7
  Release.key.8
  Release.key.9
  modules/administration/pages/ansible-integration.adoc
  modules/client-configuration/pages/clients-slemicro.adoc
Labels: master, manager-4.2, manager-4.3

#2260 Update versioning for PostgreSQL, Leap and Salt and Migration info
  modules/installation-and-upgrade/pages/db-intro.adoc
  modules/installation-and-upgrade/pages/db-migration-xy.adoc
  parameters.yml
Labels: uyuni-2023.06

#2289 Spell Cobbler with a capital C
  modules/administration/pages/troubleshooting/tshoot-highsynctimesoverwan.adoc
  modules/common-workflows/pages/workflow-inplace-sles-upgrade.adoc
  modules/retail/pages/containerized-saltboot.adoc
Labels: master

#2287 fix syntax
  modules/administration/pages/ansible-setup-control-node.adoc
Labels: manager-4.3

#2290 Normalize Virtualization chapter in Client Configuration Guide
  .changelog
  modules/client-configuration/pages/virt-xenkvm.adoc
Labels: master

#2288 uyuni: opensuse leap and sle micro 5.4 support
  .changelog
  modules/administration/pages/ansible-setup-control-node.adoc
  modules/administration/pages/live-patching-channel-setup.adoc
  modules/client-configuration/pages/client-upgrades-product-migration.adoc
  modules/client-configuration/pages/clients-slemicro.adoc
  modules/common-workflows/pages/workflow-sp-upgrade-webui.adoc
  modules/installation-and-upgrade/pages/connect-payg.adoc
  modules/installation-and-upgrade/pages/db-intro.adoc
  modules/installation-and-upgrade/pages/install-proxy.adoc
  modules/installation-and-upgrade/pages/install-vm.adoc
  modules/installation-and-upgrade/pages/proxy-registration.adoc
  modules/installation-and-upgrade/pages/pubcloud-setup.adoc
  modules/installation-and-upgrade/pages/server-y.adoc
  modules/installation-and-upgrade/pages/uyuni-install-requirements.adoc
  modules/quickstart/pages/install-uyuni-server.adoc
  modules/quickstart/pages/quickstart-install-suma-proxy.adoc
  modules/quickstart/pages/quickstart-install-uyuni-server.adoc
  modules/retail/pages/retail-install-unified.adoc
  parameters.yml
Labels: master

#2296 Fixing missing TOC. Existing pages tidy up.
  .changelog
  modules/reference/pages/spacecmd/activationkey.adoc
  modules/reference/pages/spacecmd/clear.adoc
  modules/reference/pages/spacecmd/clear_caches.adoc
  modules/reference/pages/spacecmd/misc-help-topics.adoc
  modules/reference/pages/spacecmd/repo.adoc
  modules/reference/pages/spacecmd/report.adoc
  modules/reference/pages/spacecmd/scap.adoc
  modules/reference/pages/spacecmd/schedule.adoc
  modules/reference/pages/spacecmd/snippet.adoc
  modules/reference/pages/spacecmd/softwarechannel.adoc
  modules/reference/pages/spacecmd/ssm.adoc
  modules/reference/pages/spacecmd/system.adoc
  modules/reference/pages/spacecmd/toggle.adoc
  modules/reference/pages/spacecmd/user.adoc
  modules/reference/pages/spacecmd/whoami.adoc
  modules/reference/pages/spacecmd/whoamitalkingto.adoc
Labels: master, manager-4.3

#2209 Ccg liberty boot #1207809 keichwa
  modules/client-configuration/pages/clients-sleses.adoc
  modules/client-configuration/pages/contact-methods-saltbundle.adoc
Labels: master

#2321 16GB memory minimum for server installation
  .changelog
  modules/installation-and-upgrade/pages/hardware-requirements.adoc
  modules/installation-and-upgrade/pages/install-ibmz.adoc
  modules/installation-and-upgrade/pages/install-vm.adoc
  modules/installation-and-upgrade/pages/uyuni-install-requirements.adoc
Labels: master

#2333 Update connect-payg.adoc
  modules/installation-and-upgrade/pages/connect-payg.adoc
Labels: bug
