Repository uyuni-project/uyuni-docs, pull requests merged in 2024-10, with the labels that each got.

#3360 added lifecycle admonition for BYOS
  modules/specialized-guides/pages/public-cloud-guide/payg/payg-overview.adoc
Labels: enhancement, 5.0

#3249 Iau hwreq lvm #24918 keichwa
  CHANGELOG.md
  modules/installation-and-upgrade/pages/hardware-requirements.adoc
Labels: master, manager-5.0

#3369 Uyuni qs proxy fix jcayouette
  CHANGELOG.md
  modules/installation-and-upgrade/pages/container-deployment/uyuni/migrate-uyuni-to-a-container.adoc
  modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-deployment-uyuni.adoc
  modules/installation-and-upgrade/pages/container-deployment/uyuni/proxy-migration-uyuni.adoc
  modules/installation-and-upgrade/pages/container-deployment/uyuni/server-deployment-uyuni.adoc
  modules/quickstart/pages/container-deployment/uyuni/quickstart-deploy-uyuni-proxy.adoc
  modules/quickstart/pages/container-deployment/uyuni/quickstart-deploy-uyuni-server.adoc
Labels: master, uyuni-2024.10
